### ISSUE TITLE
Angular 11 compatibility

### ISSUE THREAD

**Issue by mattia85** [renamoo/ng-simple-carousel#9]
Hello,
i'm going to update angular to version 11, is this library compatible with it?

Thank you,
Mattia

**Comment by renamoo** [comment]
@mattia85 Hi mattia, sorry I haven't noticed this comment for a while. In my understanding, Angular does not recommend to enable Ivy in the library and this library follows that so it should be compatible with Angular 11. Please feel free to let me know if any issue comes up :)
